---
- name: Add users using external IdP for authentication
  hosts: ipaserver
  become: false
  gather_facts: false

  vars:
    user_list:
      - rafasgj
      - octocat

  tasks:
    - ansible.builtin.include_tasks:
        file: tasks_add_user_from_github.yml
      loop: "{{ user_list }}"
      loop_control:
        loop_var: github_login
...
